# Generated by Django 4.2.3 on 2026-05-09 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_choice_submission_question_choice_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='contenuto',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='corso',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='punteggio',
            new_name='grade',
        ),
    ]
